version: '3.8'
volumes:
  db_mysql:
services:
  db:
    image: mysql:8.0.29
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "3606:3306"
    volumes:
      - db_mysql:/var/lib/mysql
