version: '3.8'
services:
  db:
    image: mariadb:10.8.3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
  api:
    image: conduit:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
