version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  api:
    image: conduit:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
