basePath: /api
definitions:
  api.LoginParams:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  api.RegisterParams:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  auth.LoginResponse:
    properties:
      user:
        $ref: '#/definitions/types.User'
    type: object
  auth.RegisterUserResponse:
    properties:
      user:
        $ref: '#/definitions/types.User'
    type: object
  types.User:
    properties:
      bio:
        type: string
      email:
        type: string
      image:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  utils.ErrorResponse:
    type: object
host: localhost:5000
info:
  contact: {}
  title: Conduit
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: register user params
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.RegisterParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RegisterUserResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: User registration
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login user params
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: User login
      tags:
      - Users
swagger: "2.0"
