basePath: /api
host: localhost:5000
info:
  contact: {}
  title: Conduit
  version: "1.0"
paths:
  /users:
    post:
      produces:
      - application/json
      responses: {}
      summary: User registration
      tags:
      - Users
  /users/login:
    post:
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Users
swagger: "2.0"
